# Generated by Django 5.2.8 on 2025-12-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Bio placeholder'),
            preserve_default=False,
        ),
    ]
